# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q92dBX_Q6II9dKTU-uP5M1vuNK_8jCQE
"""

import streamlit as st
import pandas as pd
import joblib
import numpy as np
import matplotlib.pyplot as plt

# ------------------------------
# Cargar modelo entrenado y OHE
# ------------------------------
modelo = joblib.load("pipeline_mlp_final.pkl")
ohe_cargado = joblib.load("one_hot_encoder.pkl")

# ------------------------------
# Funciones de agrupación
# ------------------------------
def agrupar_fuente(fuente):
    grupos = {
       'Medios_Digitales_Online': [
        'Página Web', 'FACEBOOK', 'Link', 'Correo Directo',
        'Pantalla Publicitaria Led', 'Banner','Instagram'
    ],
    'Redes_Personales_Boca_Boca': [
        'Amigos', 'Familiares', 'Estudiante', 'Docente',
        'Egresado', 'Funcionario', 'Referido Universidad Cooperat', 'Embajador Corpaeda'
    ],
    'Eventos_Ferias': [
        'Feria Universitaria', 'Visita a Colegi', 'Guías Orientación Profesional'
    ],
    'Medios_Tradicionales_Masivos': [
        'Prensa', 'Televisión', 'Radio', 'Valla', 'Pasacalle',
        'Paradero Transporte', 'Transporte Masivo', 'Directorio Telefónico'
    ]
    # Si hubiera categorías no mapeadas, se podrían dejar como están o agruparlas en 'Otro'
    }
    for grupo, valores in grupos.items():
        if fuente in valores:
            return grupo
    return "Otro"

def agrupar_pago(pago):
    grupos = {
        'Credito_Financ_Externa': [
        'Crédito ICETEX',
        'Financ por Banco o Cooperativa',
        'Crédito Coop. Comuna'
    ],
    'Pago_Directo_Propio': [
        'Contado / Efectivo',
        'Tarjeta de Crédito',
        'Fondo de Cesantias'
    ],
    'Apoyo_Beneficio': [
        'Beca',
        'Subsidio Empresarial'
    ],
        "Otro": ["Otro"]
    }
    for grupo, valores in grupos.items():
        if pago in valores:
            return grupo
    return "Otro"


# ------------------------------
# Configuración de la app
# ------------------------------
st.set_page_config(page_title="Prototipo Contaduría Pública", page_icon="🎓", layout="centered")

st.markdown("<h1 style='text-align:center; color:#d62828;'>🎯 Prototipo de Predicciones</h1>", unsafe_allow_html=True)
st.markdown("<h3 style='text-align:center; color:#003049;'>Aspirantes Contaduría Pública</h3>", unsafe_allow_html=True)
st.write("Introduce los datos del aspirante para obtener la probabilidad de **admisión / matrícula**.")

# ------------------------------
# Entrada de datos
# ------------------------------
col1, col2 = st.columns(2)

with col1:
    matematicas = st.slider("📘 Puntaje Matemáticas", 0, 100, 60)
    ciencias = st.slider("🔬 Puntaje Ciencias", 0, 100, 50)
    ingles = st.slider("🇬🇧 Puntaje Inglés", 0, 100, 60)
    lectura = st.slider("📖 Puntaje Lectura Crítica", 0, 100, 55)
    sociales = st.slider("🌍 Puntaje Sociales", 0, 100, 70)

with col2:
    estrato = st.selectbox("🏠 Estrato", [1, 2, 3, 4, 5, 6])
    trabaja = st.selectbox("💼 Trabaja Actualmente", ["Si", "No"])
    edad = st.number_input("🎂 Edad de inscripción", min_value=15, max_value=70, value=18)
    distancia = st.number_input("📍 Distancia a la universidad (km)", min_value=0, max_value=200, value=10)
    posible_pago_raw = st.selectbox("💳 Posible forma de pago", [
        "Contado / Efectivo", "Tarjeta de Crédito", "Fondo de Cesantias",
        "Crédito ICETEX", "Financ por Banco o Cooperativa",
        "Crédito Coop. Comuna", "Beca", "Subsidio Empresarial", "Otro"
    ])
    fuente_raw = st.selectbox("📢 Fuente de referencia", [
        "Página Web", "FACEBOOK", "Correo Directo", "Banner", "Instagram",
        "Amigos", "Familiares", "Docente", "Egresado", "Feria Universitaria",
        "Televisión", "Radio", "Otro"
    ])
    anio = st.number_input("📅 Año de inscripción", min_value=2020, max_value=2030, value=2025)
    semestre = st.selectbox("📚 Semestre", ["01", "02"])

# ------------------------------
# Preprocesamiento
# ------------------------------
df_nuevo = pd.DataFrame({
    'Edad inscripcion': [edad],
    'Ciencias': [ciencias],
    'Inglés': [ingles],
    'Lectura Crítica': [lectura],
    'Matematicas': [matematicas],
    'Sociales': [sociales],
    'Distancia a Universidad (km)': [distancia],
    'Año': [anio],
    'Trabaja Actualmente': [trabaja],
    'Estrato': [estrato],
    'Fuente Referencia': [agrupar_fuente(fuente_raw)],
    'Posible Forma de Pago': [agrupar_pago(posible_pago_raw)],
    'Semestre': [semestre]
})



# Transformación con OHE (ajustado al entrenamiento)
categorical_cols = ['Trabaja Actualmente', 'Estrato', 'Fuente Referencia', 'Posible Forma de Pago','Semestre']
numerical_cols = [col for col in df_nuevo.columns if col not in categorical_cols]
# Forzar que todas las categóricas sean string (igual que en entrenamiento)
for col in categorical_cols:
    df_nuevo[col] = df_nuevo[col].astype(str)

datos_encoded = ohe_cargado.transform(df_nuevo[categorical_cols])
encoded_df = pd.DataFrame(datos_encoded, columns=ohe_cargado.get_feature_names_out())

df_final = pd.concat([
    df_nuevo.drop(columns=["Estrato", "Trabaja Actualmente", "Fuente Referencia", "Posible Forma de Pago", "Semestre"]).reset_index(drop=True),
    encoded_df.reset_index(drop=True)
], axis=1)

# Reordenar según el modelo
if hasattr(modelo, "feature_names_in_"):
    df_final = df_final.reindex(columns=modelo.feature_names_in_, fill_value=0)

# ------------------------------
# Predicción
# ------------------------------
if st.button("🔮 Predecir"):
    pred = modelo.predict(df_final)[0]
    prob = modelo.predict_proba(df_final)[0][1]

    st.markdown("## 📌 Resultado de la predicción")

    col1, col2 = st.columns([1,2])

    with col1:
        st.metric(label="Clase predicha", value="✅ Matrícula" if pred==1 else "❌ Admisión")

    with col2:
        st.progress(int(prob*100))
        st.write(f"**Probabilidad de matrícula:** {prob:.2f}")

    # Gráfico circular de probabilidad
    fig, ax = plt.subplots()
    ax.pie([prob, 1-prob], labels=["Matrícula", "Admisión"], autopct="%1.1f%%", colors=["#2a9d8f", "#e76f51"])
    ax.set_title("Distribución de probabilidad")
    st.pyplot(fig)

    # Explicación textual
    if prob >= 0.6:
        st.success("El modelo estima una **alta probabilidad** de matrícula.")
    elif prob >= 0.4:
        st.warning("El modelo estima una **probabilidad intermedia**. Requiere atención adicional.")
    else:
        st.error("El modelo estima una **baja probabilidad** de matrícula.")